name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:            # least‑privilege
  contents: read
  pull-requests: read

jobs:
  build-and-analyse:
    runs-on: ubuntu-latest

    steps:
      # 1 — Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # full history for blame & PR decoration

      # 2 — Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'    # any LTS is fine
          cache: 'npm'

      # 3 — Install deps
      - run: npm ci

      # 4 — Run tests & generate coverage (lcov)
      - name: Run tests and generate coverage
        run: npm test -- --coverage


      # 5 — SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.test.js
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
